const quiz = [

{cat:"General Knowledge", q:"How many total islands/islets/rocky outcrops are there in the Andaman & Nicobar Islands as per the Andaman and Nicobar Administration?", opts:["836","1002","742","612"], ans:"836", marks:1},
{cat:"General Knowledge", q:"Which organisation does the Ministry of Rural Development cooperate with for rural development in Asia and the Pacific?", opts:["Asian Development Bank (ADB)","African-Asian Rural Development Organization (AARDO)","Centre on Integrated Rural Development for Asia and Pacific (CIRDAP)","World Bank"], ans:"Centre on Integrated Rural Development for Asia and Pacific (CIRDAP)", marks:1},
{cat:"General Knowledge", q:"Which of the following letter-clusters should replace # and % so that the pattern and relationship followed between the letter-cluster pair on the left side of :: is the same as that on the right side of ::? # : QVR :: CHD : %", opts:["# = LQM, % = HMI","# = PMM, % = JUY","# = LJM, % = NHG","# = GYT, % = NYU"], ans:"# = LJM, % = NHG", marks:1},
{cat:"General Knowledge", q:"Read the given statements and conclusions carefully. Assuming that the information given in the statements is true, decide which of the given conclusions logically follow(s): All jams are bands. All bands are sacks. No sack is a can. Conclusions: (I) No jam is a can. (II) Some sacks are jams.", opts:["Neither conclusion (I) nor (II) follows.","Only conclusion (I) follows.","Only conclusion (II) follows.","Both conclusions (I) and (II) follow."], ans:"Both conclusions (I) and (II) follow.", marks:1},
{cat:"General Knowledge", q:"Which country ranked highest overall in the Climate Change Performance Index 2025?", opts:["Germany","France","Denmark","Sweden"], ans:"Denmark", marks:1},
{cat:"General Knowledge", q:"NASA astronaut Sunita Williams returned to Earth in March 2025 after her mission aboard a SpaceX capsule. How much time had she spent in space?", opts:["608 days","502 days","212 days","578 days"], ans:"502 days", marks:1},
{cat:"General Knowledge", q:"Select the set in which the numbers are related in the same way as are the numbers of the following sets: (33, 429, 13) and (44, 220, 5)", opts:["(20, 363, 18)","(43, 903, 21)","(30, 363, 12)","(4, 23, 5)"], ans:"(30, 363, 12)", marks:1},
{cat:"General Knowledge", q:"In March 2025, which health milestone was remembered on National Vaccination Day?", opts:["Pulse Polio First Dose","National Vax Mission","Polio Eradication Drive","Launch of COVID Vaccine"], ans:"Pulse Polio First Dose", marks:1},
{cat:"General Knowledge", q:"If 1 is added to each odd digit and 2 is subtracted from each even digit in the number 5673128, what will be the difference between the digits which are third from the left and second from the right in the new number thus formed?", opts:["9","6","7","8"], ans:"7", marks:1},
{cat:"General Knowledge", q:"If 3 times the mother's present age is 36 years more than 5 times her daughter's age, and 3 times the daughter's age is 4 years less than the mother's age, then what is the difference (in years) between their present ages?", opts:["13","20","16","18"], ans:"16", marks:1},
{cat:"General Knowledge", q:"A shopkeeper marked his goods at X% above their cost price and sold them at a discount of 10%. If he gained 71% profit, then find the value of X.", opts:["91","89","92","90"], ans:"90", marks:1},
{cat:"General Knowledge", q:"Find the missing value (Q.12).", opts:["18.7","18.9","19.9","19.5"], ans:"19.5", marks:1},
{cat:"General Knowledge", q:"What should come in place of the question mark (?) in the given series based on the English alphabetical order: NTZ LRX JPV HNT ?", opts:["RLF","FRL","FLR","RFL"], ans:"FRL", marks:1},
{cat:"General Knowledge", q:"Which of the following is NOT an industrial corridor planned under the Government of India’s infrastructure initiatives?", opts:["Kolkata-Lucknow Industrial Corridor","Chennai-Bengaluru Industrial Corridor","Vizag-Chennai Industrial Corridor","Delhi-Mumbai Industrial Corridor"], ans:"Kolkata-Lucknow Industrial Corridor", marks:1},
{cat:"General Knowledge", q:"A, B, C, D, E and F live on six different floors of a building. The product of floors on which F and D live is 15. E lives immediately above C. The sum of floors of A and D is 7. What is the sum of floors on which A and E live?", opts:["6","5","8","7"], ans:"8", marks:1},
{cat:"General Knowledge", q:"If 1 is added to each odd digit and 2 is subtracted from each even digit in the number 8271634, how many digits will appear more than once in the new number thus formed?", opts:["Two","None","One","Three"], ans:"One", marks:1},
{cat:"General Knowledge", q:"Deepesh has 168 litres of Oil A and 234 litres of Oil B. He fills identical containers with only one type of oil in each. What can be the maximum volume (in litres) of each container so that all the oil can be poured exactly?", opts:["10","6","14","5"], ans:"6", marks:1},
{cat:"General Knowledge", q:"What type of farming is practised in hill regions by cutting slopes into steps?", opts:["Mixed farming","Extensive farming","Wetland farming","Terrace farming"], ans:"Terrace farming", marks:1},
{cat:"General Knowledge", q:"The length, width and height of a cuboid are in the ratio 10 : 17 : 14, and its total surface area is 1096 cm². Find the length (in cm) of the cuboid.", opts:["17","10","1","5"], ans:"10", marks:1},
{cat:"General Knowledge", q:"Which of the following letter-number clusters will replace the question mark (?) in the given series: NQ31, MP40, LO49, KN58, ?", opts:["JN66","JN67","JM67","JM66"], ans:"JM67", marks:1},

 ]
