const quiz = [
  {cat:"Mathematics", q:"Find the remainder when 3^{100} is divided by 50.", opts:["0","1","49","25"], ans:"49", marks:1},
  {cat:"Mathematics", q:"The average of three consecutive even numbers is 42. Find the largest number.", opts:["42","44","46","40"], ans:"44", marks:1},
  {cat:"Mathematics", q:"If a train covers 120 km in 1 hour 30 minutes, what is its average speed in km/h?", opts:["60","80","100","120"], ans:"80", marks:1},
  {cat:"Mathematics", q:"If cost price = ₹800 and selling price = ₹920, find the profit percentage.", opts:["10%","12%","15%","8%"], ans:"15%", marks:1},
  {cat:"Mathematics", q:"A and B can complete a work in 10 and 15 days respectively. In how many days can they complete it together?", opts:["5","6","7","8"], ans:"6", marks:1},
  {cat:"Mathematics", q:"If 40% of x = 50% of 80, find x.", opts:["60","80","100","120"], ans:"100", marks:1},
  {cat:"Mathematics", q:"The ratio of speeds of two trains is 3:5. Find the ratio of times taken to cover the same distance.", opts:["3:5","5:3","9:25","25:9"], ans:"5:3", marks:1},
  {cat:"Mathematics", q:"If 2 men or 3 women can do a job in 12 days, then 6 men and 9 women can complete it in how many days?", opts:["2","3","4","6"], ans:"2", marks:1},
  {cat:"Mathematics", q:"A sum becomes ₹800 in 2 years and ₹880 in 3 years at simple interest. Find the principal.", opts:["₹720","₹800","₹880","₹760"], ans:"₹720", marks:1},
  {cat:"Mathematics", q:"A train 150 m long passes a man standing on a platform in 6 seconds. Find the speed of the train (km/h).", opts:["60","75","90","100"], ans:"90", marks:1},
  {cat:"Mathematics", q:"The difference between simple and compound interest on ₹10,000 for 2 years at 10% per annum is:", opts:["₹10","₹100","₹50","₹150"], ans:"₹100", marks:1},
  {cat:"Mathematics", q:"If a pipe fills a tank in 12 hours and another empties it in 18 hours, how long to fill the tank together?", opts:["36 hr","20 hr","36/5 hr","36/7 hr"], ans:"36 hr", marks:1},
  {cat:"Mathematics", q:"The area of a circle is 616 cm². Find its radius (π = 22/7).", opts:["14","10","12","16"], ans:"14", marks:1},
  {cat:"Mathematics", q:"A train crosses a 300 m platform in 24 s and a man in 18 s. Find the length of the train.", opts:["150 m","200 m","250 m","300 m"], ans:"200 m", marks:1},
  {cat:"Mathematics", q:"Average of 3 numbers is 68. If one number is 64, find average of the other two.", opts:["69","68","67","70"], ans:"69", marks:1},
  {cat:"Mathematics", q:"If ₹1200 amounts to ₹1800 in 3 years, find the rate of interest per annum.", opts:["15%","18%","20%","25%"], ans:"16.66%", marks:1},
  {cat:"Mathematics", q:"The cost of 8 pens and 4 pencils is ₹84. The cost of 2 pens and 2 pencils is ₹26. Find the cost of one pen.", opts:["₹6","₹7","₹8","₹9"], ans:"₹8", marks:1},
  {cat:"Mathematics", q:"Two numbers are in the ratio 5:7. Their difference is 24. Find the numbers.", opts:["60,84","50,74","65,89","55,79"], ans:"60,84", marks:1},
  {cat:"Mathematics", q:"A person travels 40 km at 20 km/h and another 40 km at 80 km/h. Find average speed.", opts:["32 km/h","36 km/h","40 km/h","48 km/h"], ans:"32 km/h", marks:1},
  {cat:"Mathematics", q:"If a train increases its speed by 10 km/h, it reaches 15 minutes early. If its normal speed is 40 km/h, find distance.", opts:["40 km","50 km","60 km","70 km"], ans:"50 km", marks:1},
  {cat:"Mathematics", q:"The population of a town increases by 5% annually. If present population is 21000, find it 2 years ago.", opts:["₹18000","₹19000","₹19047","₹20000"], ans:"₹19047", marks:1},
  {cat:"Mathematics", q:"A man spends 70% of his income. If his income increases by 25%, his savings increase by 50%. Find his savings percentage initially.", opts:["10%","20%","25%","30%"], ans:"20%", marks:1},
  {cat:"Mathematics", q:"If 3 workers can make 90 toys in 6 days, how many toys can 5 workers make in 9 days?", opts:["180","200","225","250"], ans:"225", marks:1},
  {cat:"Mathematics", q:"A sum of ₹10,000 is compounded annually at 10%. Find the amount after 2 years.", opts:["₹11,000","₹12,000","₹12,100","₹12,200"], ans:"₹12,100", marks:1},
  {cat:"Mathematics", q:"The ratio of the ages of A and B is 3:4. After 5 years, it will be 4:5. Find their present ages.", opts:["15,20","20,25","21,28","24,32"], ans:"15,20", marks:1},
  {cat:"Mathematics", q:"A train leaves Delhi at 6 a.m. at 60 km/h and another at 7 a.m. at 90 km/h. When will the second train catch the first?", opts:["9 a.m.","10 a.m.","11 a.m.","12 noon"], ans:"9 a.m.", marks:1},
  {cat:"Mathematics", q:"A rectangular park is 60 m long and 40 m wide. Find its area and perimeter.", opts:["2400,200","2600,200","2400,220","2000,200"], ans:"2400,200", marks:1},
  {cat:"Mathematics", q:"A car covers 200 km with an average speed of 50 km/h. Find the time taken.", opts:["2 hr","3 hr","4 hr","5 hr"], ans:"4 hr", marks:1},
  {cat:"Mathematics", q:"If the perimeter of a square is 64 m, find its area.", opts:["256","128","144","196"], ans:"256", marks:1},
  {cat:"Mathematics", q:"The sum of first 10 odd numbers is:", opts:["90","100","110","120"], ans:"100", marks:1},
  {cat:"Mathematics", q:"The least number to be added to 2055 to make it a perfect square is:", opts:["24","25","26","36"], ans:"25", marks:1},
  {cat:"Mathematics", q:"If the perimeter of a circle equals the perimeter of a square of side 14 cm, find the radius of the circle (π = 22/7).", opts:["7","9","10","14"], ans:"9", marks:1},
  {cat:"Mathematics", q:"The mean of 6, 7, 8, 9, 10, and 11 is:", opts:["7.5","8","8.5","9"], ans:"8.5", marks:1},
  {cat:"Reasoning", q:"If A is the brother of B and B is the sister of C, how is A related to C?", opts:["Brother","Sister","Father","Cannot be determined"], ans:"Brother", marks:1},
  {cat:"Reasoning", q:"Find the missing term in the series: 3, 9, 27, ?, 243.", opts:["54","72","81","108"], ans:"81", marks:1},
  {cat:"Reasoning", q:"If '+' means '−', '−' means '×', '×' means '÷', and '÷' means '+', find the value of 32 ÷ 14 + 16 − 8 × 4.", opts:["14","16","18","22"], ans:"16", marks:1},
  {cat:"Reasoning", q:"Which letter-cluster pair is different? XMB, YNC, ZOD, APP.", opts:["XMB","YNC","ZOD","APP"], ans:"APP", marks:1},
  {cat:"Reasoning", q:"Find the odd one out: 25, 36, 49, 64, 80.", opts:["25","36","49","80"], ans:"80", marks:1},
  {cat:"Reasoning", q:"If in a code, CAT = 24, DOG = 26, then BAT = ?", opts:["22","23","24","25"], ans:"22", marks:1},
  {cat:"Reasoning", q:"Choose the word which can be formed from the letters of 'EXAMINATION'.", opts:["NATION","MINT","EXAM","NOTE"], ans:"NATION", marks:1},
  {cat:"Reasoning", q:"If 5 * 2 = 27, 7 * 3 = 58, then 6 * 4 = ?", opts:["38","40","46","52"], ans:"46", marks:1},
  {cat:"Reasoning", q:"Which number will complete the series? 7, 14, 28, 56, ?", opts:["70","84","98","112"], ans:"112", marks:1},
  {cat:"Reasoning", q:"If SOUTH is written as 53124 and NORTH as 94124, then SNORT is written as:", opts:["59314","95134","95314","59134"], ans:"95314", marks:1},
  {cat:"Reasoning", q:"Find the next number: 1, 4, 9, 16, 25, ?", opts:["36","49","64","81"], ans:"36", marks:1},
  {cat:"Reasoning", q:"Arrange in dictionary order: (a) Mango, (b) Man, (c) Manage, (d) Mansion.", opts:["b, c, d, a","b, d, c, a","b, c, a, d","b, a, c, d"], ans:"b, c, a, d", marks:1},
  {cat:"Reasoning", q:"If TABLE = 39, CHAIR = 40, what is STOOL?", opts:["56","58","60","62"], ans:"60", marks:1},
  {cat:"Reasoning", q:"If P = 16, R = 18, S = 19, find value of TRAIN.", opts:["74","75","76","77"], ans:"75", marks:1},
  {cat:"Reasoning", q:"A walks North 4 km, then East 3 km. Distance from starting point?", opts:["5 km","6 km","7 km","8 km"], ans:"5 km", marks:1},
  {cat:"Reasoning", q:"Pointing to a man, Neha said, 'He is my father's only son.' How is Neha related to that man?", opts:["Father","Sister","Daughter","Mother"], ans:"Daughter", marks:1},
  {cat:"Reasoning", q:"Select the related word pair: Bird : Nest :: Bee : ?", opts:["Web","Hive","Colony","Burrow"], ans:"Hive", marks:1},
  {cat:"Reasoning", q:"In a certain code, FIRE = 45, then COLD = ?", opts:["27","28","29","30"], ans:"28", marks:1},
  {cat:"Reasoning", q:"Find the missing number: 8, 27, 64, ?, 216.", opts:["81","100","125","144"], ans:"125", marks:1},
  {cat:"Reasoning", q:"Which one does not belong to the group? Apple, Mango, Banana, Carrot.", opts:["Apple","Mango","Banana","Carrot"], ans:"Carrot", marks:1},
  {cat:"Reasoning", q:"In a family, A is father of B, B is sister of C, C is father of D. How is A related to D?", opts:["Grandfather","Father","Uncle","Brother"], ans:"Grandfather", marks:1},
  {cat:"Reasoning", q:"In a clock, the hands coincide every:", opts:["11 min","11 1/11 min","12 min","13 min"], ans:"11 1/11 min", marks:1},
  {cat:"Reasoning", q:"Find the odd one: 8–27, 27–64, 64–125, 125–216, 216–343.", opts:["8–27","27–64","125–216","216–343"], ans:"216–343", marks:1},
  {cat:"Reasoning", q:"Complete the analogy: Doctor : Hospital :: Teacher : ?", opts:["School","Temple","Office","Library"], ans:"School", marks:1},
  {cat:"Reasoning", q:"If 9 + 3 = 36, 8 + 4 = 48, then 6 + 5 = ?", opts:["50","55","60","65"], ans:"60", marks:1},
  {cat:"Reasoning", q:"Find the missing term: 13, 17, 19, 23, ?", opts:["25","27","29","31"], ans:"29", marks:1},
  {cat:"Reasoning", q:"Choose the correct mirror image of 'NIT' seen in a mirror.", opts:["TIИ","TIN","IИT","NIT"], ans:"TIИ", marks:1},
  {cat:"Reasoning", q:"A is heavier than B, B is lighter than C. D is heavier than C. Who is lightest?", opts:["A","B","C","D"], ans:"B", marks:1},
  {cat:"Reasoning", q:"Five friends are standing in a line. P is left of Q, R is right of Q. If S is right of R and T is left of P, who is in the middle?", opts:["Q","R","P","S"], ans:"Q", marks:1},
  {cat:"Reasoning", q:"If all the vowels in the word COMPUTER are changed to next letter in English alphabet, how many consonants remain unchanged?", opts:["2","3","4","5"], ans:"4", marks:1},
  {cat:"Reasoning", q:"Which shape will complete the pattern series: ■, ▲, ●, ■, ▲, ?", opts:["●","■","▲","◆"], ans:"●", marks:1},
  {cat:"Reasoning", q:"If 7 = 56, 6 = 42, 5 = 30, then 9 = ?", opts:["63","72","81","90"], ans:"72", marks:1},
  {cat:"Reasoning", q:"Which day of the week was 26 Jan 1950?", opts:["Thursday","Friday","Saturday","Monday"], ans:"Thursday", marks:1},
  {cat:"Reasoning", q:"In a code, EXAM = FYBN, then TEST = ?", opts:["UFUT","UFTU","UETT","UFST"], ans:"UFTU", marks:1},
  {cat:"Railway GK", q:"When did the first train run in India?", opts:["1851","1853","1855","1857"], ans:"1853", marks:1},
  {cat:"Railway GK", q:"Between which stations did India's first train operate?", opts:["Mumbai–Thane","Chennai–Arcot","Howrah–Hooghly","Delhi–Agra"], ans:"Mumbai–Thane", marks:1},
  {cat:"Railway GK", q:"Who was the first female loco pilot in Indian Railways?", opts:["Surekha Yadav","Preeti Kumari","Mamta Banerjee","Anjali Sharma"], ans:"Surekha Yadav", marks:1},
  {cat:"Railway GK", q:"Which is the largest railway zone in India by route length?", opts:["Northern Railway","Western Railway","Eastern Railway","Central Railway"], ans:"Northern Railway", marks:1},
  {cat:"Railway GK", q:"Where is the headquarters of South Eastern Railway?", opts:["Kolkata","Chennai","Hyderabad","Bhubaneswar"], ans:"Kolkata", marks:1},
  {cat:"Railway GK", q:"Which Indian mountain railway is a UNESCO World Heritage Site?", opts:["Darjeeling Himalayan Railway","Nilgiri Mountain Railway","Kalka–Shimla Railway","All of these"], ans:"All of these", marks:1},
  {cat:"Railway GK", q:"In which year was the separate Railway Budget merged with the General Budget?", opts:["2016","2017","2018","2019"], ans:"2017", marks:1},
  {cat:"Railway GK", q:"IRCTC stands for:", opts:["Indian Railway Catering and Tourism Corporation","Indian Railway Construction Company","Indian Railway Coach Technology Centre","None of these"], ans:"Indian Railway Catering and Tourism Corporation", marks:1},
  {cat:"Railway GK", q:"Where is the National Rail Museum located?", opts:["New Delhi","Mumbai","Kolkata","Chennai"], ans:"New Delhi", marks:1},
  {cat:"Railway GK", q:"Which is the busiest railway station in India?", opts:["Howrah Junction","Chhatrapati Shivaji Maharaj Terminus","Delhi Junction","Kanpur Central"], ans:"Howrah Junction", marks:1},
  {cat:"Railway GK", q:"What does RDSO stand for?", opts:["Research Designs and Standards Organisation","Railway Development System Office","Rolling Design Service Organisation","Railway Design Standards Office"], ans:"Research Designs and Standards Organisation", marks:1},
  {cat:"Railway GK", q:"Which railway station was India's first redeveloped airport-like terminal?", opts:["Gandhinagar Capital","Habibganj","Surat","Lucknow"], ans:"Gandhinagar Capital", marks:1},
  {cat:"Railway GK", q:"Which train is classified as a semi-high-speed express?", opts:["Vande Bharat Express","Rajdhani Express","Duronto Express","Shatabdi Express"], ans:"Vande Bharat Express", marks:1},
  {cat:"Railway GK", q:"Approximate top operational speed of Vande Bharat Express?", opts:["130 km/h","140 km/h","160 km/h","180 km/h"], ans:"160 km/h", marks:1},
  {cat:"Railway GK", q:"Which technology is used in Vande Bharat for automatic doors and distributed power?", opts:["Distributed Power Technology","Hydraulic Traction","Magnetic Levitation","Vacuum Drive"], ans:"Distributed Power Technology", marks:1},
  {cat:"Railway GK", q:"Dedicated Freight Corridors (DFC) are constructed between:", opts:["Delhi–Mumbai & Ludhiana–Dankuni","Delhi–Kolkata & Mumbai–Chennai","Delhi–Ahmedabad & Mumbai–Pune","Delhi–Varanasi & Chennai–Bengaluru"], ans:"Delhi–Mumbai & Ludhiana–Dankuni", marks:1},
  {cat:"Railway GK", q:"Which system provides automatic train protection in India?", opts:["KAVACH","Raksha","Suraksha","Guard AI"], ans:"KAVACH", marks:1},
  {cat:"Railway GK", q:"What is the main source of power for electric locomotives?", opts:["Overhead Catenary","Diesel Engine","Battery Pack","Solar Panel"], ans:"Overhead Catenary", marks:1},
  {cat:"Railway GK", q:"As of 2024, approximately what percent of railway routes are electrified?", opts:["75%","80%","85%","95%"], ans:"85%", marks:1},
  {cat:"Railway GK", q:"Target year for 100% electrification of rail routes?", opts:["2025","2027","2030","2032"], ans:"2025", marks:1},
  {cat:"Railway GK", q:"Indian Railways earns highest revenue from:", opts:["Freight Transport","Passenger Tickets","Catering","Tourism"], ans:"Freight Transport", marks:1},
  {cat:"Railway GK", q:"Which city inaugurated India's longest railway platform in 2024?", opts:["Hubballi","Vadodara","Secunderabad","Nagpur"], ans:"Hubballi", marks:1},
  {cat:"Railway GK", q:"Which organisation manages Metro systems in most Indian cities?", opts:["State Metro Corporations","IRCTC","Railway Board","Urban Transport Mission"], ans:"State Metro Corporations", marks:1},
  {cat:"Railway GK", q:"Which app provides live tracking and train enquiry services?", opts:["NTES","RailYatri","IRCTC Next","RailRadar"], ans:"NTES", marks:1},
  {cat:"Railway GK", q:"Indian Railway Finance Corporation (IRFC) deals primarily with:", opts:["Raising funds for rail projects","Recruitment","Ticketing","Freight monitoring"], ans:"Raising funds for rail projects", marks:1},
  {cat:"Railway GK", q:"Which is the largest railway workshop in India?", opts:["Perambur","Kharagpur","Varanasi","Jamalpur"], ans:"Perambur", marks:1},
  {cat:"Railway GK", q:"Which city houses the Integral Coach Factory (ICF)?", opts:["Chennai","Kolkata","Bhopal","Delhi"], ans:"Chennai", marks:1},
  {cat:"Railway GK", q:"Konkan Railway connects which regions?", opts:["Mumbai–Goa–Mangalore","Kolkata–Bhubaneswar–Chennai","Delhi–Jaipur–Ahmedabad","Pune–Nagpur–Raipur"], ans:"Mumbai–Goa–Mangalore", marks:1},
  {cat:"Railway GK", q:"Which force protects railway passengers and property?", opts:["RPF","CRPF","GRP","CISF"], ans:"RPF", marks:1},
  {cat:"Railway GK", q:"Which of the following is a green initiative of Indian Railways?", opts:["Bio-toilets","Solar panels","LED lighting","All of these"], ans:"All of these", marks:1},
  {cat:"Railway GK", q:"Which is India's first bullet train project corridor?", opts:["Mumbai–Ahmedabad","Delhi–Varanasi","Chennai–Bengaluru","Delhi–Amritsar"], ans:"Mumbai–Ahmedabad", marks:1},
  {cat:"Railway GK", q:"Which train uses Tilting Technology in India?", opts:["Train 18","Rajdhani Express","Duronto Express","Shatabdi Express"], ans:"Train 18", marks:1},
  {cat:"Railway GK", q:"Which locomotive factory produces electric engines at Madhepura?", opts:["Alstom India","Siemens","BHEL","RDSO"], ans:"Alstom India", marks:1}
];
