const quiz = [
  {cat:"Ratio and Proportion", q:"The ratio of the speeds of two trains is 3:5. If the first covers 300 km in 5 hours, how long will the second take to cover 500 km?", opts:["6 h","5 h","4 h","3 h"], ans:"5 h", marks:1},
  {cat:"Simple Interest", q:"Find the simple interest on ₹4000 at 5% per annum for 3 years.", opts:["₹400","₹500","₹600","₹700"], ans:"₹600", marks:1},
  {cat:"Compound Interest", q:"₹10000 is invested at 10% per annum compounded annually. Find the amount after 2 years.", opts:["₹11000","₹12000","₹12100","₹12200"], ans:"₹12100", marks:1},
  {cat:"Time and Work", q:"A, B, and C can complete a track-laying job in 20, 30, and 60 days respectively. If A leaves after 5 days and B after 10 days, how long will C take to finish the remaining work?", opts:["10 days","12 days","15 days","18 days"], ans:"15 days", marks:1},
  {cat:"Percentages", q:"In a railway canteen, the price of food items increased by 25%. If a worker spends ₹600 now, how much did he spend before the increase?", opts:["₹400","₹450","₹480","₹500"], ans:"₹480", marks:1},
  {cat:"Profit and Loss", q:"A contractor purchased railway spare parts for ₹8000 and sold them for ₹9600. Find the profit percent.", opts:["10%","15%","18%","20%"], ans:"20%", marks:1},
  {cat:"Trains", q:"A train 200 m long passes a platform 300 m long in 30 seconds. Find its speed.", opts:["60 km/h","72 km/h","90 km/h","108 km/h"], ans:"60 km/h", marks:1},
  {cat:"LCM and HCF", q:"Find the LCM and HCF of 24 and 90.", opts:["LCM=360, HCF=6","LCM=180, HCF=12","LCM=360, HCF=12","LCM=240, HCF=8"], ans:"LCM=360, HCF=6", marks:1},
  {cat:"Mensuration", q:"Find the area of a platform 50 m long and 10 m wide.", opts:["400 m²","450 m²","500 m²","550 m²"], ans:"500 m²", marks:1},
  {cat:"Algebra", q:"If x + 1/x = 5, find x² + 1/x².", opts:["23","24","25","26"], ans:"23", marks:1},
  {cat:"Trigonometry", q:"If sinθ = 3/5, find cosθ.", opts:["4/5","5/4","3/4","4/3"], ans:"4/5", marks:1},
  {cat:"Geometry", q:"The perimeter of a square railway signboard is 64 cm. Find its area.", opts:["64 cm²","128 cm²","256 cm²","512 cm²"], ans:"256 cm²", marks:1},
  {cat:"Statistics", q:"Find the mean of 10, 20, 30, 40, 50.", opts:["25","30","35","40"], ans:"30", marks:1},
  {cat:"Simplification", q:"Simplify: (15% of 240) + (12.5% of 320).", opts:["72","75","78","80"], ans:"78", marks:1},
  {cat:"Mixture", q:"A 50-litre fuel mixture has 30% diesel. How much diesel should be added to make it 40%?", opts:["10 L","8 L","6 L","5 L"], ans:"10 L", marks:1},
  {cat:"Boats and Streams", q:"A boat goes 12 km downstream in 2 hours and returns in 3 hours. Find the speed of the stream.", opts:["1 km/h","2 km/h","3 km/h","4 km/h"], ans:"1 km/h", marks:1},
  {cat:"Pipes and Cisterns", q:"Pipe A fills a tank in 12 hours, and Pipe B fills it in 15 hours. Together they fill it in how many hours?", opts:["6h 40m","6h 30m","6h","7h"], ans:"6h 40m", marks:1},
  {cat:"Probability", q:"A train's engine fails with probability 0.02 on a trip. What is the probability it works fine?", opts:["0.02","0.08","0.9","0.98"], ans:"0.98", marks:1},
  {cat:"Averages", q:"The average speed of a train for 4 hours at 60 km/h and 2 hours at 90 km/h is?", opts:["65 km/h","70 km/h","72 km/h","75 km/h"], ans:"70 km/h", marks:1},
  {cat:"Partnership", q:"A invests ₹50000 and B invests ₹40000 in a railway contract. Profit is ₹18000. Find A's share.", opts:["₹9000","₹10000","₹10500","₹12000"], ans:"₹10000", marks:1},
  {cat:"Mensuration", q:"Find the curved surface area of a cylinder of radius 7 m and height 10 m.", opts:["220 m²","440 m²","770 m²","880 m²"], ans:"440 m²", marks:1},
  {cat:"Number System", q:"Find the smallest number which when divided by 12, 15, and 18 leaves remainder 3.", opts:["183","183","183","183"], ans:"183", marks:1},
  {cat:"Geometry", q:"The diagonals of a rhombus are 24 cm and 10 cm. Find its area.", opts:["100 cm²","120 cm²","150 cm²","240 cm²"], ans:"120 cm²", marks:1},
  {cat:"Trains", q:"Two trains 100 m and 120 m long cross each other in 10 seconds while running in opposite directions at equal speed. Find each train's speed.", opts:["36 km/h","54 km/h","60 km/h","72 km/h"], ans:"54 km/h", marks:1},
  {cat:"Profit and Loss", q:"A vendor marks up railway tools by 25% and allows 10% discount. Find profit percent.", opts:["12.5%","13.5%","14%","15%"], ans:"12.5%", marks:1},
  {cat:"Simple Interest", q:"Find the principal if SI = ₹540, rate = 9% p.a., time = 2 years.", opts:["₹3000","₹3200","₹3500","₹4000"], ans:"₹3000", marks:1},
  {cat:"Mensuration", q:"Find the volume of a cuboid 5 m × 4 m × 3 m.", opts:["60 m³","70 m³","80 m³","90 m³"], ans:"60 m³", marks:1},
  {cat:"Percentage", q:"In a railway budget, capital outlay increased from ₹2000 crore to ₹2400 crore. Find the % increase.", opts:["10%","15%","20%","25%"], ans:"20%", marks:1},
  {cat:"Ratio", q:"Two engines pull a train such that their power ratio is 3:2. If the first engine pulls 1800 N, find total pull.", opts:["3000 N","4500 N","4800 N","5000 N"], ans:"3000 N", marks:1},
  {cat:"Data Interpretation", q:"In a pie chart showing freight distribution, 40% goods are coal, 30% steel, 30% others. If total freight is 2000 tonnes, how much coal is carried?", opts:["400","600","800","1000"], ans:"800", marks:1},
  {cat:"Analogy", q:"Signal is to Train as Green Light is to ?", opts:["Stop","Platform","Go","Track"], ans:"Go", marks:1},
  {cat:"Series Completion", q:"Find the missing term: 3, 6, 12, 24, ?", opts:["36","40","46","48"], ans:"48", marks:1},
  {cat:"Odd One Out", q:"Choose the odd one out: Diesel, Coal, Steam, Track", opts:["Diesel","Coal","Steam","Track"], ans:"Track", marks:1},
  {cat:"Coding-Decoding", q:"If TRAIN is coded as 21691, how is RAIL coded?", opts:["9121","1912","9211","9112"], ans:"9112", marks:1},
  {cat:"Blood Relation", q:"A says to B: 'You are my brother's father's son.' How is B related to A?", opts:["Brother","Cousin","Father","Son"], ans:"Brother", marks:1},
  {cat:"Direction Sense", q:"A guard walks 200 m east, then 150 m south, then 200 m west. Find his distance from the start point.", opts:["50 m","100 m","150 m","200 m"], ans:"150 m", marks:1},
  {cat:"Alphabet Series", q:"Find the missing letter: A, D, I, P, ?", opts:["U","V","W","X"], ans:"Y", marks:1},
  {cat:"Number Series", q:"Find the next term: 2, 6, 12, 20, 30, ?", opts:["36","40","42","44"], ans:"42", marks:1},
  {cat:"Seating Arrangement", q:"Six employees A, B, C, D, E, F sit in a row facing north. If A is right of B and left of C, D is at extreme right, who sits in the middle?", opts:["C","B","E","A"], ans:"E", marks:1},
  {cat:"Venn Diagram", q:"Select the best diagram for: Drivers, Men, Employees", opts:["Triangle","Circle","Overlapping Circles","Separate Circles"], ans:"Overlapping Circles", marks:1},
  {cat:"Syllogism", q:"Statements: All trains are vehicles. Some vehicles are buses. Conclusions: I. Some trains are buses. II. All buses are vehicles.", opts:["Only II follows","Only I follows","Both follow","Neither follows"], ans:"Only II follows", marks:1},
  {cat:"Decision Making", q:"A train is delayed by fog. Should the driver overspeed to recover time?", opts:["Yes","No","Partially","Data insufficient"], ans:"No", marks:1},
  {cat:"Data Sufficiency", q:"Question: What is the code for 'train'? Statement I: 'train arrives late' is coded as 426. Statement II: 'arrives station early' is coded as 467. Options:", opts:["Only I","Only II","Both I & II","Either I or II"], ans:"Both I & II", marks:1},
  {cat:"Analytical Reasoning", q:"Five coaches — S1, S2, S3, S4, S5 — are arranged. S3 is not adjacent to S2 or S5. S4 is between S1 and S5. Which is in the middle?", opts:["S1","S3","S4","S2"], ans:"S4", marks:1},
  {cat:"Number Coding", q:"If DELHI = 52, MUMBAI = 64, find value of CHENNAI.", opts:["70","72","74","76"], ans:"74", marks:1},
  {cat:"Calendar", q:"If 1 January 2021 was Friday, what day was 1 January 2024?", opts:["Saturday","Monday","Wednesday","Thursday"], ans:"Monday", marks:1},
  {cat:"Missing Number", q:"Find missing number: 4 8 12, 6 12 18, 8 16 ?", opts:["20","22","24","26"], ans:"24", marks:1},
  {cat:"Direction Test", q:"A signalman faces north. He turns right, walks 10 m, left 15 m, left 10 m. Find final direction.", opts:["North","South","East","West"], ans:"West", marks:1},
  {cat:"Logical Order", q:"Arrange logically: (A) Passenger enters, (B) Ticket checked, (C) Train departs, (D) Train arrives.", opts:["B-A-D-C","A-B-D-C","B-A-C-D","A-B-C-D"], ans:"B-A-C-D", marks:1},
  {cat:"Matrix Reasoning", q:"Find missing number in the matrix:\n4 6 8\n3 9 27\n2 ? 8", opts:["4","6","8","10"], ans:"4", marks:1},
  {cat:"Cause & Effect", q:"Statement I: Train delayed due to signal failure. Statement II: Signal maintenance not done. Choose the relation.", opts:["I is cause, II is effect","II is cause, I is effect","Independent","Common cause"], ans:"II is cause, I is effect", marks:1},
  {cat:"Puzzle", q:"Four trains — A, B, C, D — arrive at platform 1 to 4. A arrives before B, C after D, B after C. Which arrives last?", opts:["A","B","C","D"], ans:"B", marks:1},
  {cat:"Pattern Recognition", q:"Find next pattern: 2, 5, 10, 17, 26, ?", opts:["35","37","40","41"], ans:"37", marks:1},
  {cat:"Arithmetic Reasoning", q:"A train moves 120 km in 3 hours. Another moves 240 km in 6 hours. Compare speeds.", opts:["Equal","First faster","Second faster","Cannot be compared"], ans:"Equal", marks:1},
  {cat:"Calendar", q:"If 26th January 2023 was Thursday, what day was 26th January 2024?", opts:["Friday","Saturday","Sunday","Thursday"], ans:"Friday", marks:1},
  {cat:"Clock", q:"At what time between 2 and 3 o'clock will the hands be together?", opts:["2:27","2:28","2:29","2:30"], ans:"2:27", marks:1},
  {cat:"Statement–Assumption", q:"Statement: Railway should improve track safety. Assumption: Tracks are unsafe.", opts:["True","False","Implicit","Not implicit"], ans:"Implicit", marks:1},
  {cat:"Statement–Conclusion", q:"Statement: More express trains introduced. Conclusion: Passenger travel time reduced.", opts:["Follows","Does not follow","Partly follows","Indeterminate"], ans:"Partly follows", marks:1},
  {cat:"Ranking", q:"In a queue of 20 passengers, R is 8th from front. How many are behind R?", opts:["11","12","13","14"], ans:"12", marks:1},
  {cat:"Coding Pattern", q:"If RAIL = 181212, how is TRAIN coded?", opts:["20201814","20181214","20181418","None"], ans:"20181214", marks:1},
  {cat:"Symbol-Operation", q:"If A@B means A is 2 more than B, and A#B means A is 3 less than B, then 5@x#10 = ?", opts:["x=8","x=9","x=10","x=12"], ans:"x=9", marks:1},
  {cat:"Direction", q:"A driver travels 4 km north, 3 km west, 2 km south. What is the shortest distance to return?", opts:["5 km","6 km","7 km","8 km"], ans:"5 km", marks:1},
  {cat:"Logical Puzzle", q:"Five trains P–T arrive sequentially. P before R, S after Q, Q before T. If R arrives before S, which train is 3rd?", opts:["P","Q","R","S"], ans:"R", marks:1},
  {cat:"Inference", q:"Statement: Railway tracks require periodic inspection. Inference: Maintenance ensures safety.", opts:["Valid","Invalid","Weak","False"], ans:"Valid", marks:1},
  {cat:"Indian Railways", q:"When was Indian Railways founded?", opts:["1853","1845","1869","1901"], ans:"1853", marks:1},
  {cat:"Railway Zones", q:"Which is the largest railway zone in India by route length?", opts:["Northern Railway","Western Railway","Eastern Railway","South Central Railway"], ans:"Northern Railway", marks:1},
  {cat:"Railway HQ", q:"Where is the headquarters of the South Eastern Railway located?", opts:["Kolkata","Bhubaneswar","Chennai","Nagpur"], ans:"Kolkata", marks:1},
  {cat:"Railway Fact", q:"Where did the first train in India run?", opts:["Mumbai to Thane","Delhi to Agra","Kolkata to Raniganj","Chennai to Arakkonam"], ans:"Mumbai to Thane", marks:1},
  {cat:"Railway Projects", q:"Dedicated Freight Corridors (DFC) are being constructed between which two pairs of terminals?", opts:["Delhi–Mumbai & Ludhiana–Dankuni","Delhi–Kolkata & Chennai–Hyderabad","Mumbai–Chennai & Delhi–Bengaluru","Kolkata–Guwahati & Delhi–Patna"], ans:"Delhi–Mumbai & Ludhiana–Dankuni", marks:1},
  {cat:"Railway Safety", q:"Which system in Indian Railways is used for automatic train protection?", opts:["KAVACH","KALYAN","SURAKSHA","PRAGATI"], ans:"KAVACH", marks:1},
  {cat:"Railway Electrification", q:"As of 2024, approx. what percentage of Indian Railway routes are electrified?", opts:["95%","85%","75%","60%"], ans:"85%", marks:1},
  {cat:"Railway Trains", q:"Vande Bharat Express operates under which category?", opts:["Semi-high speed","Bullet train","Superfast Express","MEMU"], ans:"Semi-high speed", marks:1},
  {cat:"Railway Minister", q:"Who is the current Minister of Railways (as of 2025)?", opts:["Ashwini Vaishnaw","Piyush Goyal","Suresh Prabhu","Nitin Gadkari"], ans:"Ashwini Vaishnaw", marks:1},
  {cat:"Railway Heritage", q:"Which Indian mountain railway is a UNESCO World Heritage Site?", opts:["Darjeeling Himalayan Railway","Konkan Railway","Nilgiri Express","Northeast Frontier Railway"], ans:"Darjeeling Himalayan Railway", marks:1},
  {cat:"Railway Budget", q:"In which year was the separate Railway Budget merged with the General Budget?", opts:["2017","2015","2014","2018"], ans:"2017", marks:1},
  {cat:"Railway PSU", q:"IRCTC stands for?", opts:["Indian Railway Catering and Tourism Corporation","Indian Railway Construction Company","Integrated Railway Communication Corporation","Indian Rail Cargo and Transport Company"], ans:"Indian Railway Catering and Tourism Corporation", marks:1},
  {cat:"Railway Network", q:"India ranks ______ in the world in terms of railway network size.", opts:["4th","2nd","3rd","5th"], ans:"4th", marks:1},
  {cat:"Railway Museum", q:"The National Rail Museum is located in:", opts:["New Delhi","Mumbai","Chennai","Nagpur"], ans:"New Delhi", marks:1},
  {cat:"Railway Station", q:"Which is the busiest railway station in India?", opts:["Howrah Junction","New Delhi","Chhatrapati Shivaji Terminus","Kanpur Central"], ans:"Howrah Junction", marks:1},
  {cat:"Railway Awards", q:"Who was the first female loco pilot of Indian Railways?", opts:["Surekha Yadav","Kalpana Chawla","Harita Kaur","Priti Singh"], ans:"Surekha Yadav", marks:1},
  {cat:"Railway Coach", q:"The Integral Coach Factory (ICF) is located at:", opts:["Chennai","Bhopal","Lucknow","Patiala"], ans:"Chennai", marks:1},
  {cat:"Railway Policy", q:"What is the target year for India to achieve 100% electrification of rail routes?", opts:["2025","2027","2030","2024"], ans:"2025", marks:1},
  {cat:"Railway Safety", q:"What does the acronym RDSO stand for?", opts:["Research Designs and Standards Organisation","Railway Development and Security Office","Railway Data and Safety Organisation","Research Department for Signal Operations"], ans:"Research Designs and Standards Organisation", marks:1},
  {cat:"Railway Modernization", q:"Which railway station was redeveloped as the first airport-like terminal in India?", opts:["Gandhinagar Capital","Bhopal Junction","Habibganj","Vapi"], ans:"Gandhinagar Capital", marks:1},
  {cat:"Railway Freight", q:"Indian Railways primarily earns the highest revenue from:", opts:["Freight transport","Passenger fares","Tourism trains","Parcel services"], ans:"Freight transport", marks:1},
  {cat:"Railway Speed", q:"Approximate top operational speed of Vande Bharat Express is:", opts:["160 km/h","200 km/h","250 km/h","300 km/h"], ans:"160 km/h", marks:1},
  {cat:"Indian Polity", q:"The Railway Board functions under which ministry?", opts:["Ministry of Railways","Ministry of Transport","Ministry of Commerce","Ministry of Heavy Industries"], ans:"Ministry of Railways", marks:1},
  {cat:"General Science", q:"What is the main source of power for an electric locomotive?", opts:["Overhead catenary","Diesel fuel","Battery pack","Solar roof"], ans:"Overhead catenary", marks:1},
  {cat:"Computers", q:"The digital ticketing system of Indian Railways primarily runs through which portal?", opts:["IRCTC","RailTel","BharatNet","NIC"], ans:"IRCTC", marks:1},
  {cat:"Transport", q:"Which authority manages Metro rail systems in most Indian cities?", opts:["Urban Development Ministry","State Metro Corporations","NITI Aayog","Railway Board"], ans:"State Metro Corporations", marks:1},
  {cat:"Railway Finance", q:"The Indian Railway Finance Corporation (IRFC) mainly deals with:", opts:["Raising funds for railway projects","Passenger fare collection","Coach design","Ticketing system"], ans:"Raising funds for railway projects", marks:1},
  {cat:"Current Affairs", q:"In 2024, which city inaugurated India's longest railway platform?", opts:["Hubballi","Kharagpur","Varanasi","Nagpur"], ans:"Hubballi", marks:1},
  {cat:"Railway Technology", q:"Which technology is used in Vande Bharat for automatic doors and control?", opts:["Distributed power technology","Push-pull system","Diesel-electric hybrid","Maglev"], ans:"Distributed power technology", marks:1},
  {cat:"Indian Geography", q:"Konkan Railway mainly connects which regions?", opts:["Mumbai–Goa–Mangalore","Delhi–Agra–Kanpur","Chennai–Hyderabad","Kolkata–Bhubaneswar"], ans:"Mumbai–Goa–Mangalore", marks:1},
  {cat:"Environment", q:"Which of the following is a green initiative of Indian Railways?", opts:["Solar-powered coaches","Bio-diesel engines","All of these","LED lighting"], ans:"All of these", marks:1},
  {cat:"Railway Security", q:"Which force is responsible for the protection of railway passengers and property?", opts:["RPF","CRPF","BSF","CISF"], ans:"RPF", marks:1},
  {cat:"Railway App", q:"Which app provides live tracking and train enquiry services?", opts:["NTES","RailTel","UMANG","Bharat Rail"], ans:"NTES", marks:1}
];
